const MARK_AS_READ = "MARK_AS_READ";
const SET_TYPE_FILTER = "SET_TYPE_FILTER";
const NotificationTypeFilters = {
    DEFAULT: "DEFAULT",
    URGENT: "URGENT"
};
const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
const SET_LOADING_STATE = "SET_LOADING_STATE";

export {
    MARK_AS_READ,
    SET_TYPE_FILTER,
    NotificationTypeFilters,
    FETCH_NOTIFICATIONS_SUCCESS,
    SET_LOADING_STATE
};